version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - security-net

  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - security-net

  zap:
    image: owasp/zap2docker-stable
    ports:
      - "8080:8080"
    command: zap-baseline.py -t http://webapp:3000
    networks:
      - security-net

networks:
  security-net:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions: 